/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbs;

/**
 *
 * @author maree
 */
import connectionprovider.ConnectionProvider;
import javax.swing.*;
import java.sql.*;
import java.math.*;
public class adddall extends javax.swing.JFrame {

    /**
     * Creates new form adddall
     */
    public adddall() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        industryname = new javax.swing.JTextField();
        hsncode = new javax.swing.JTextField();
        bagnum = new javax.swing.JTextField();
        packnum = new javax.swing.JTextField();
        dallquantity = new javax.swing.JTextField();
        dallrate = new javax.swing.JTextField();
        name = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\maree\\Downloads\\red-yellow-green-lentils-brown-bowls-black-stone-table-top-view.jpg")); // NOI18N
        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("ADD DALL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setText("DALL INDUSTRY NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 241, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("DALL NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, 241, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setText("HSN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 220, 241, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setText("BAGS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, 241, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setText("PACKING");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 320, 241, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel7.setText("QUANTITY");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 370, 241, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel8.setText("RATE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, 241, -1));

        industryname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        industryname.setText("ENTER DALL INDUSTRY NAME");
        industryname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                industrynameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                industrynameFocusLost(evt);
            }
        });
        industryname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                industrynameActionPerformed(evt);
            }
        });
        getContentPane().add(industryname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 120, 260, -1));

        hsncode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hsncode.setText("ENTER HSN CODE");
        hsncode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hsncodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hsncodeFocusLost(evt);
            }
        });
        hsncode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hsncodeActionPerformed(evt);
            }
        });
        getContentPane().add(hsncode, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 220, 262, -1));

        bagnum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bagnum.setText("ENTER NUMBER OF BAGS");
        bagnum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bagnumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bagnumFocusLost(evt);
            }
        });
        bagnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagnumActionPerformed(evt);
            }
        });
        getContentPane().add(bagnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 270, 262, -1));

        packnum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        packnum.setText("ENTER NUMBER OF PACKING");
        packnum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                packnumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                packnumFocusLost(evt);
            }
        });
        packnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packnumActionPerformed(evt);
            }
        });
        getContentPane().add(packnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 320, 262, -1));

        dallquantity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dallquantity.setText("ENTER QUANTITY");
        dallquantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dallquantityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dallquantityFocusLost(evt);
            }
        });
        getContentPane().add(dallquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 370, 262, -1));

        dallrate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dallrate.setText("ENTER RATE");
        dallrate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dallrateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dallrateFocusLost(evt);
            }
        });
        dallrate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dallrateActionPerformed(evt);
            }
        });
        getContentPane().add(dallrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 420, 262, -1));

        name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TOOR DAL", "MASOOR DAL", "CHANA DALL", "MOONG DAL", "URAD DAL", "RAJMA", "CHAWLI", "MOTH BEANS" }));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 170, 262, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 550, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 550, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton3.setText("CLOSE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 550, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton4.setText("ADD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 550, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\maree\\Downloads\\wooden-bowl-spoons-raw-red-lentils-stone-background_114579-59244.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hsncodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hsncodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hsncodeActionPerformed

    private void bagnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bagnumActionPerformed

    private void packnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packnumActionPerformed

    private void industrynameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_industrynameFocusGained
        // TODO add your handling code here:
        if(industryname.getText().equals("ENTER DALL INDUSTRY NAME"))
        {
            industryname.setText("");
        }
    }//GEN-LAST:event_industrynameFocusGained

    private void industrynameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_industrynameFocusLost
        // TODO add your handling code here:
        if(industryname.getText().equals(""))
        {
            industryname.setText("ENTER DALL INDUSTRY NAME");
        }
    }//GEN-LAST:event_industrynameFocusLost

    private void hsncodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hsncodeFocusGained
        // TODO add your handling code here:
        if(hsncode.getText().equals("ENTER HSN CODE"))
        {
            hsncode.setText("");
        }
    }//GEN-LAST:event_hsncodeFocusGained

    private void hsncodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hsncodeFocusLost
        // TODO add your handling code here:
        if(hsncode.getText().equals(""))
        {
            hsncode.setText("ENTER HSN CODE");
        }
    }//GEN-LAST:event_hsncodeFocusLost

    private void bagnumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bagnumFocusGained
        // TODO add your handling code here:
        if(bagnum.getText().equals("ENTER NUMBER OF BAGS"))
        {
            bagnum.setText("");
        }
    }//GEN-LAST:event_bagnumFocusGained

    private void bagnumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bagnumFocusLost
        // TODO add your handling code here:
        if(bagnum.getText().equals(""))
        {
            bagnum.setText("ENTER NUMBER OF BAGS");
        }
    }//GEN-LAST:event_bagnumFocusLost

    private void packnumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_packnumFocusGained
        // TODO add your handling code here:
        if(packnum.getText().equals("ENTER NUMBER OF PACKING"))
        {
            packnum.setText("");
        }
    }//GEN-LAST:event_packnumFocusGained

    private void packnumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_packnumFocusLost
        // TODO add your handling code here:
        if(packnum.getText().equals(""))
        {
            packnum.setText("ENTER NUMBER OF PACKING");
        }
    }//GEN-LAST:event_packnumFocusLost

    private void dallquantityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dallquantityFocusGained
        // TODO add your handling code here:
        if(dallquantity.getText().equals("ENTER QUANTITY"))
        {
            dallquantity.setText("");
        }
    }//GEN-LAST:event_dallquantityFocusGained

    private void dallquantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dallquantityFocusLost
        // TODO add your handling code here:
        if(dallquantity.getText().equals(""))
        {
            dallquantity.setText("ENTER QUANTITY");
        }
    }//GEN-LAST:event_dallquantityFocusLost

    private void dallrateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dallrateFocusGained
        // TODO add your handling code here:
        if(dallrate.getText().equals("ENTER RATE"))
        {
            dallrate.setText("");
        }
    }//GEN-LAST:event_dallrateFocusGained

    private void dallrateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dallrateFocusLost
        // TODO add your handling code here:
        if(dallrate.getText().equals(""))
        {
            dallrate.setText("ENTER RATE");
        }
    }//GEN-LAST:event_dallrateFocusLost

    private void industrynameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_industrynameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_industrynameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new adddall().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String dall_industry = industryname.getText();
        String dname= (String)name.getSelectedItem();
        BigInteger hsn = new BigInteger(hsncode.getText());
        int bags = Integer.parseInt(bagnum.getText());
        int packing = Integer.parseInt(packnum.getText());
        int quantity = Integer.parseInt(dallquantity.getText());
        BigDecimal rate = new BigDecimal(dallrate.getText());
        BigDecimal amount = rate.multiply(new BigDecimal(quantity));

        
        
        
        try {
            Connection con = ConnectionProvider.getConnection();
            if (con == null) {
                JOptionPane.showMessageDialog(null, "Failed to establish a database connection.");
                 return;
            }
            String query;
            query = "INSERT INTO dall_supplier(dall_industry,dall_name,hsn,bags,packing,quantity,rate,amount) VALUES (?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, dall_industry);
            pst.setString(2, dname);
            pst.setBigDecimal(3, new BigDecimal(hsn));
            pst.setInt(4, bags);
            pst.setInt(5, packing);
            pst.setInt(6, quantity);
            pst.setBigDecimal(7, rate);   
            pst.setBigDecimal(8, amount);

            //pst.setString(9, quality1);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully Added");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dallrateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dallrateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dallrateActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            String dname= (String)name.getSelectedItem();
            int quantity = Integer.parseInt(dallquantity.getText());
            Connection con = ConnectionProvider.getConnection();
            String query1 ="select quantity from dall_details where d_name=?";
            PreparedStatement pst1 = con.prepareStatement(query1);
            pst1.setString(1, dname);
            ResultSet rs1 = pst1.executeQuery();
            boolean found = false; 
        
            if (rs1.next()) {
                int existingquantity=rs1.getInt("quantity");
                int newquantity=existingquantity+quantity;
                String query2="update dall_details set quantity=? where d_name=?";
                PreparedStatement pst2=con.prepareStatement(query2);
                pst2.setInt(1,newquantity);
                pst2.setString(2,dname);
                pst2.executeUpdate();
                found=true;
                JOptionPane.showMessageDialog(null, "Successfully Added To Dhall Details Table");
            }
            if (!found) {
                String query;
                query = "INSERT INTO dall_details(d_name,quantity) VALUES (?,?)";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, dname);
                pst.setInt(2, quantity);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Successfully Added To Dhall Details Table");
                
                
            }
        }
        catch(NumberFormatException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());

        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adddall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adddall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adddall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adddall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            @Override
            public void run() {
                new adddall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bagnum;
    private javax.swing.JTextField dallquantity;
    private javax.swing.JTextField dallrate;
    private javax.swing.JTextField hsncode;
    private javax.swing.JTextField industryname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> name;
    private javax.swing.JTextField packnum;
    // End of variables declaration//GEN-END:variables
}
