/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbs;

/**
 *
 * @author maree
 */
import connectionprovider.ConnectionProvider;
import javax.swing.*;
import java.sql.*;
import java.math.*;
public class addlorrydetails extends javax.swing.JFrame {

    /**
     * Creates new form addlorrydetails
     */
    public addlorrydetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        industryname = new javax.swing.JTextField();
        ownername = new javax.swing.JTextField();
        drivername = new javax.swing.JTextField();
        lorrynum = new javax.swing.JTextField();
        phonenum = new javax.swing.JTextField();
        qtil = new javax.swing.JTextField();
        freights = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("ADD LORRY DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 29, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setText("DALL INDUSTRY NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 125, 243, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("LORRY OWNER NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 174, 243, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setText("LORRY DRIVER NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 223, 243, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setText("LORRY NUMBER");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 269, 243, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setText("PHONE NUMBER");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 309, 243, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel7.setText("TOTAL QTILS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 358, 243, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel8.setText("FRIEGHTS PER QTILS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 407, 243, -1));

        industryname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        industryname.setText("ENTER DALL INDUSTRY NAME");
        industryname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                industrynameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                industrynameFocusLost(evt);
            }
        });
        industryname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                industrynameActionPerformed(evt);
            }
        });
        getContentPane().add(industryname, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 122, 308, -1));

        ownername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ownername.setText("ENTER LORRY OWNER NAME");
        ownername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ownernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ownernameFocusLost(evt);
            }
        });
        getContentPane().add(ownername, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 171, 308, -1));

        drivername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        drivername.setText("ENTER LORRY DRIVER NAME");
        drivername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                drivernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                drivernameFocusLost(evt);
            }
        });
        getContentPane().add(drivername, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 220, 308, -1));

        lorrynum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lorrynum.setText("ENTER LORRY NUMBER");
        lorrynum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lorrynumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lorrynumFocusLost(evt);
            }
        });
        lorrynum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lorrynumActionPerformed(evt);
            }
        });
        getContentPane().add(lorrynum, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 269, 308, -1));

        phonenum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phonenum.setText("ENTER PHONE NUMBER");
        phonenum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phonenumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phonenumFocusLost(evt);
            }
        });
        getContentPane().add(phonenum, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 306, 308, -1));

        qtil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        qtil.setText("ENTER TOTAL QTIL ");
        qtil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                qtilFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                qtilFocusLost(evt);
            }
        });
        qtil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtilActionPerformed(evt);
            }
        });
        getContentPane().add(qtil, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 355, 308, -1));

        freights.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        freights.setText("ENTER FREIGHTS PER QTIL\n");
        freights.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                freightsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                freightsFocusLost(evt);
            }
        });
        getContentPane().add(freights, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 404, 308, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 511, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 511, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton3.setText("CLOSE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 511, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\maree\\Downloads\\two-kinds-raw-beans-lentils-wooden-plate-bowls_114579-30455.jpg")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qtilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtilActionPerformed

    private void lorrynumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lorrynumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lorrynumActionPerformed

    private void industrynameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_industrynameFocusGained
        // TODO add your handling code here:
        if(industryname.getText().equals("ENTER DALL INDUSTRY NAME"))
        {
            industryname.setText("");
        }

    }//GEN-LAST:event_industrynameFocusGained

    private void industrynameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_industrynameFocusLost
        // TODO add your handling code here:
        if(industryname.getText().equals(""))
        {
            industryname.setText("ENTER DALL INDUSTRY NAME");
        }
    }//GEN-LAST:event_industrynameFocusLost

    private void ownernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ownernameFocusGained
        // TODO add your handling code here:
        if(ownername.getText().equals("ENTER LORRY OWNER NAME"))
        {
            ownername.setText("");
        }

    }//GEN-LAST:event_ownernameFocusGained

    private void ownernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ownernameFocusLost
        // TODO add your handling code here:
        if(ownername.getText().equals(""))
        {
            ownername.setText("ENTER LORRY OWNER NAME");
        }
    }//GEN-LAST:event_ownernameFocusLost

    private void drivernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_drivernameFocusGained
        // TODO add your handling code here:
        if(drivername.getText().equals("ENTER LORRY DRIVER NAME"))
        {
            drivername.setText("");
        }

    }//GEN-LAST:event_drivernameFocusGained

    private void drivernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_drivernameFocusLost
        // TODO add your handling code here:
        if(drivername.getText().equals(""))
        {
            drivername.setText("ENTER LORRY DRIVER NAME");
        }
    }//GEN-LAST:event_drivernameFocusLost

    private void lorrynumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lorrynumFocusGained
        // TODO add your handling code here:
        if(lorrynum.getText().equals("ENTER LORRY NUMBER"))
        {
            lorrynum.setText("");
        }

    }//GEN-LAST:event_lorrynumFocusGained

    private void lorrynumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lorrynumFocusLost
        // TODO add your handling code here:
        if(lorrynum.getText().equals(""))
        {
           lorrynum.setText("ENTER LORRY NUMBER");
        }
    }//GEN-LAST:event_lorrynumFocusLost

    private void phonenumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phonenumFocusGained
        // TODO add your handling code here:
        if(phonenum.getText().equals("ENTER PHONE NUMBER"))
        {
            phonenum.setText("");
        }

    }//GEN-LAST:event_phonenumFocusGained

    private void phonenumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phonenumFocusLost
        // TODO add your handling code here:
        if(phonenum.getText().equals(""))
        {
            phonenum.setText("ENTER PHONE NUMBER");
        }
    }//GEN-LAST:event_phonenumFocusLost

    private void qtilFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qtilFocusGained
        // TODO add your handling code here:
        if(qtil.getText().equals("ENTER TOTAL QTIL ")){
            qtil.setText("");
        }

    }//GEN-LAST:event_qtilFocusGained

    private void qtilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qtilFocusLost
        // TODO add your handling code here:
        if(qtil.getText().equals(""))
        {
            qtil.setText("ENTER TOTAL QTIL ");
        }
    }//GEN-LAST:event_qtilFocusLost

    private void freightsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_freightsFocusGained
        // TODO add your handling code here:
        if(freights.getText().equals("ENTER FREIGHTS PER QTIL "))
        {
            freights.setText("");
        }

    }//GEN-LAST:event_freightsFocusGained

    private void freightsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_freightsFocusLost
        // TODO add your handling code here:
        if(freights.getText().equals(""))
        {
            freights.setText("ENTER FREIGHTS PER QTIL ");
        }
    }//GEN-LAST:event_freightsFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String dall_industry = industryname.getText();
        String o_name= ownername.getText();
        String d_name= drivername.getText();
        String l_num=lorrynum.getText();
        String p_num=phonenum.getText();
        BigDecimal total_qtil = new BigDecimal(qtil.getText());
        BigDecimal freights_qtil = new BigDecimal(freights.getText());
        BigDecimal amount = freights_qtil.multiply(total_qtil);

        
        
        
        try {
            Connection con = ConnectionProvider.getConnection();
            if (con == null) {
                JOptionPane.showMessageDialog(null, "Failed to establish a database connection.");
                 return;
            }
            String query;
            query = "INSERT INTO lorry(dall_industry,owner,driver,lorry_num,phone_num,qtils,freights,amount) VALUES (?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, dall_industry);
            pst.setString(2, o_name);
            pst.setString(3, d_name);
            pst.setString(4, l_num);
            pst.setString(5, p_num);
            pst.setBigDecimal(6, total_qtil);
            pst.setBigDecimal(7, freights_qtil);   
            pst.setBigDecimal(8, amount);

            //pst.setString(9, quality1);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully Added");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new addlorrydetails().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void industrynameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_industrynameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_industrynameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addlorrydetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addlorrydetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addlorrydetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addlorrydetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addlorrydetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField drivername;
    private javax.swing.JTextField freights;
    private javax.swing.JTextField industryname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lorrynum;
    private javax.swing.JTextField ownername;
    private javax.swing.JTextField phonenum;
    private javax.swing.JTextField qtil;
    // End of variables declaration//GEN-END:variables
}
