/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbs;

/**
 *
 * @author maree
 */
import java.sql.*;
import connectionprovider.ConnectionProvider;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import java.math.*;
import java.io.*;
import javax.swing.JFileChooser;
import java.awt.HeadlessException;
import javax.mail.*;
public class dealerbill extends javax.swing.JFrame {

    /**
     * Creates new form dealerbill
     */
    public dealerbill() {
        initComponents();
        SimpleDateFormat dFormat=new SimpleDateFormat("dd-mm-yyyy");
        Date date =new Date();
        jLabel22.setText(dFormat.format(date));
        
        DateTimeFormatter dtf=DateTimeFormatter.ofPattern("hh:mm:ss");
        LocalDateTime now =LocalDateTime.now();
        jLabel24.setText(dtf.format(now));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ms = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        partygstin = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        dhalltype = new javax.swing.JTextField();
        hnscode = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        totalfield = new javax.swing.JTextField();
        cgstfield = new javax.swing.JTextField();
        sgstfield = new javax.swing.JTextField();
        igstfield = new javax.swing.JTextField();
        grandTotalfield = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        rate = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setText("GSTIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel2.setText("N.C.TRADERS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 6, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("33ALVPT9260D1ZL");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setText("Prop.N.C.THANGA PANDI");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1256, 6, 245, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setText("CELL");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1256, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("9842099181");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1309, 40, 104, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel7.setText("DHALL MERCHANTS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 66, 252, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 154, 1507, 10));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel8.setText("128-B,KATCHERI ROAD,VIRUDHUNAGAR");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 170, 390, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 214, 1507, 12));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel9.setText("NO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 241, 37, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel10.setText("DATE");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 78, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel11.setText("M/S");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 295, 125, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel12.setText("ADDRESS");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 344, 125, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel13.setText("PARTY GSTIN");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 393, -1, -1));

        ms.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msActionPerformed(evt);
            }
        });
        getContentPane().add(ms, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 292, 489, -1));

        address.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 341, 489, -1));

        partygstin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        partygstin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partygstinActionPerformed(evt);
            }
        });
        getContentPane().add(partygstin, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 390, 489, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1331, 245, 96, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel14.setText("DHALL TYPE");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(847, 241, 121, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel15.setText("HNS CODE");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(847, 295, 121, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel16.setText("QUANTITY");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(847, 344, 121, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PARTICULARS", "HSN", "QUANTITY", "RATE", "AMOUNT"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 509, 797, 268));

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel17.setText("TOTAL");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 509, 157, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel18.setText("CGST");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 560, 157, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel19.setText("SGST");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 612, 157, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel20.setText("IGST");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 665, 157, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel21.setText("GRAND TOTAL");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 712, 157, -1));

        dhalltype.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dhalltype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dhalltypeActionPerformed(evt);
            }
        });
        getContentPane().add(dhalltype, new org.netbeans.lib.awtextra.AbsoluteConstraints(1037, 238, 253, -1));

        hnscode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hnscode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hnscodeActionPerformed(evt);
            }
        });
        getContentPane().add(hnscode, new org.netbeans.lib.awtextra.AbsoluteConstraints(1037, 292, 253, -1));

        quantity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        getContentPane().add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(1037, 341, 253, -1));

        totalfield.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(totalfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(1049, 509, 276, -1));

        cgstfield.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(cgstfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(1049, 560, 276, -1));

        sgstfield.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(sgstfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(1049, 609, 276, -1));

        igstfield.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        igstfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igstfieldActionPerformed(evt);
            }
        });
        getContentPane().add(igstfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(1049, 660, 276, -1));

        grandTotalfield.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(grandTotalfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(1049, 709, 276, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton2.setText("CLOSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1331, 609, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton3.setText("RESET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1331, 709, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton4.setText("SAVE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1331, 509, -1, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 488, 1507, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel22.setText("jLabel22");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 78, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel23.setText("TIME");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 116, 50, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel24.setText("jLabel24");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 116, -1, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 238, 489, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel25.setText("RATE");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(847, 393, 121, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel26.setText("AMOUNT");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(847, 442, 121, -1));

        rate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1037, 390, 253, -1));

        amount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1037, 439, 253, -1));

        jButton5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton5.setText("REMOVE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1331, 299, 96, -1));

        jButton6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton6.setText("SEND MAIL");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1331, 348, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\maree\\Downloads\\white-png-base_23-2151645368 (1).jpg")); // NOI18N
        jLabel28.setText("jLabel28");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cgstfield.setText("0.00");
        sgstfield.setText("0.00");
        igstfield.setText("0.00");
        String dname= dhalltype.getText();
        BigDecimal qty = new BigDecimal(quantity.getText());
        BigDecimal ratevalue=new BigDecimal(rate.getText());
        BigDecimal hundred = new BigDecimal("100");
        BigDecimal d_amount = qty.divide(hundred).multiply(ratevalue);
        amount.setText(d_amount.toString());
        DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
        model1.addRow(new Object[] {
        dhalltype.getText(),
        hnscode.getText(),
        quantity.getText(),
        rate.getText(),
        d_amount.toString()
    });
    try{
            Connection con = ConnectionProvider.getConnection();
            String query1 ="select quantity from dall_details where d_name=?";
            PreparedStatement pst1 = con.prepareStatement(query1);
            pst1.setString(1, dname);
            ResultSet rs1 = pst1.executeQuery();
            boolean found = false; 
        
            if (rs1.next()) {
                int existingquantity=rs1.getInt("quantity");
                int qtyint=Integer.parseInt(quantity.getText());
                int newquantity=existingquantity-qtyint;
                if(newquantity==0)
                {
                    JOptionPane.showMessageDialog(null, "Warning : quantity for"+dname+"is now zero","Stock Warning",JOptionPane.WARNING_MESSAGE);
                }
                String query2="update dall_details set quantity=? where d_name=?";
                PreparedStatement pst2=con.prepareStatement(query2);
                pst2.setInt(1,newquantity);
                pst2.setString(2,dname);
                pst2.executeUpdate();
                found=true;
            }
            BigDecimal totalamount =BigDecimal.ZERO;
            for(int i=0;i<model1.getRowCount();i++)
            {
                Object value = model1.getValueAt(i, 4);
                if(value!=null)
                {
                    try{
                        BigDecimal Amount=new BigDecimal(value.toString());
                        totalamount=totalamount.add(Amount);
                    }
                    catch(NumberFormatException e)
                    {
                    }
                }
            }
            totalfield.setText(totalamount.toString());
            BigDecimal total = parseBigDecimalSafe(totalfield.getText());
            BigDecimal cgst = parseBigDecimalSafe(cgstfield.getText());
            BigDecimal igst = parseBigDecimalSafe(igstfield.getText());
            BigDecimal sgst = parseBigDecimalSafe(sgstfield.getText());
        // Calculate grand total as sum of all
            BigDecimal grandTotal = total.add(cgst).add(igst).add(sgst);
        // Set grand total in grandTotalfield
            grandTotalfield.setText(grandTotal.toString());
    }
            
    catch(NumberFormatException | SQLException e)
    {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    private BigDecimal parseBigDecimalSafe(String s) {
    try {
        return new BigDecimal(s);
    } catch (Exception e) {
        return BigDecimal.ZERO;
    }
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void hnscodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hnscodeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_hnscodeActionPerformed

    private void msActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msActionPerformed
        // TODO add your handling code here:
        
        try
        {
            Connection con = ConnectionProvider.getConnection();
            String query="select * from dealer where d_comapny=?";
            PreparedStatement pst =con.prepareStatement(query);
            pst.setString(1, ms.getText());
            ResultSet rs=pst.executeQuery();
            if(rs.next())
            {
                ms.setText(rs.getString(1));
                address.setText(rs.getString(2));
                partygstin.setText(rs.getString(3));
            }
            else
            {
                ms.setText("");
                address.setText("");
                partygstin.setText("");
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_msActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
        try
        {
            Connection con = ConnectionProvider.getConnection();
            String query="select * from dealer where address=?";
            PreparedStatement pst =con.prepareStatement(query);
            pst.setString(1, address.getText());
            ResultSet rs=pst.executeQuery();
            if(rs.next())
            {
                ms.setText(rs.getString(1));
                address.setText(rs.getString(2));
                partygstin.setText(rs.getString(3));
            }
            else
            {
                ms.setText("");
                address.setText("");
                partygstin.setText("");
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_addressActionPerformed

    private void partygstinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partygstinActionPerformed
        // TODO add your handling code here:
        try
        {
            Connection con = ConnectionProvider.getConnection();
            String query="select * from dealer where gstin=?";
            PreparedStatement pst =con.prepareStatement(query);
            pst.setString(1, partygstin.getText());
            ResultSet rs=pst.executeQuery();
            if(rs.next())
            {
                ms.setText(rs.getString(1));
                address.setText(rs.getString(2));
                partygstin.setText(rs.getString(3));
            }
            else
            {
                ms.setText("");
                address.setText("");
                partygstin.setText("");
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_partygstinActionPerformed

    private void dhalltypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dhalltypeActionPerformed
        // TODO add your handling code here:
        
        try
        {
            Connection con = ConnectionProvider.getConnection();
            String query="select * from dall_details where d_name=?";
            PreparedStatement pst =con.prepareStatement(query);
            pst.setString(1, dhalltype.getText());
            ResultSet rs=pst.executeQuery();
            if(rs.next())
            {
                dhalltype.setText(rs.getString(1));
                hnscode.setText("0173");
                quantity.setText(rs.getString(2));
            }
            else
            {
                dhalltype.setText("");
                hnscode.setText("");
                quantity.setText("");
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_dhalltypeActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new dealerbill().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        int selectedRow=jTable1.getSelectedRow();
        if(selectedRow !=-1)
        {
            String dname=model.getValueAt(selectedRow, 0).toString();
            int quantitytoadd= Integer.parseInt(model.getValueAt(selectedRow, 2 ).toString());
            try
            {
                Connection con = ConnectionProvider.getConnection();
                String query="UPDATE dall_details Set quantity= quantity + ? WHERE d_name=?";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setInt(1, quantitytoadd); // Set the quantity to add
                pst.setString(2, dname); // Set the dall name
                int rowsupdated = pst.executeUpdate();
                if (rowsupdated > 0) {
                    JOptionPane.showMessageDialog(null, "Quantity updated successfully for " + dname);
                } else {
                    JOptionPane.showMessageDialog(null, "No matching record found for " + dname, "Warning", JOptionPane.WARNING_MESSAGE);
                }
            }
            catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            }
            
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a row to update", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        int Count=model.getRowCount();
        if(Count>0)
        {
            model.removeRow(Count -1);
            JOptionPane.showMessageDialog(null, "Last entry has been removed");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No rows to remove","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        try {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Save Bill");

            int userSelection = fileChooser.showSaveDialog(null);

            if (userSelection == JFileChooser.APPROVE_OPTION) {
                File fileToSave = fileChooser.getSelectedFile();

                try (FileWriter writer = new FileWriter(fileToSave + ".txt")) {
                    writer.write("         N.C.TRADERS – BILL\n");
                    writer.write("         DHALL MERCHANTS\n");
                    writer.write("=========================================\n");
                    writer.write("Date     : " + new java.util.Date() + "\n");
                    writer.write("Customer : " + ms.getText() + "\n");
                    writer.write("Address  : " + address.getText() + "\n");
                    writer.write("GSTIN    : " + partygstin.getText() + "\n");
                    writer.write("=========================================\n");

            // Table Header
                    writer.write(String.format("%-15s%-10s%-10s%-10s%-10s\n",
                    "Particulars", "HSN", "Qty", "Rate", "Amount"));

                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    double grandTotal = 0;

                    for (int i = 0; i < model.getRowCount(); i++) {
                        String particulars = model.getValueAt(i, 0).toString();
                        String hsn = model.getValueAt(i, 1).toString();
                        String qty = model.getValueAt(i, 2).toString();
                        String rate = model.getValueAt(i, 3).toString();
                        String amount = model.getValueAt(i, 4).toString();

                        writer.write(String.format("%-15s%-10s%-10s%-10s%-10s\n",
                            particulars, hsn, qty, rate, amount));
                        
                        grandTotal += Double.parseDouble(amount);
                        
                    }

                    writer.write("=========================================\n");
                    writer.write("CGST :"+ cgstfield.getText() +"\n");
                    writer.write("SGST : "+sgstfield.getText() +"\n");
                    writer.write("IGST : "+igstfield.getText() +"\n");
                    writer.write("-----------------------------------------\n");
                    writer.write("GRAND TOTAL : " + grandTotal + "\n");
                    writer.write("=========================================\n");

                    JOptionPane.showMessageDialog(null, "Bill saved successfully!");
                    

                }
            }
        } 
        catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error saving bill: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void igstfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igstfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_igstfieldActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String recipientEmail = javax.swing.JOptionPane.showInputDialog(this, "Enter recipient email address:");
        if (recipientEmail != null && !recipientEmail.trim().isEmpty()) {
            final String senderEmail = "veileeswaribalaji@gmail.com";
            final String senderPassword = "hjns kkxt qvyu jafc";  // Use App Password for Gmail
            String filepath;
            filepath = "D:/email/dhallbill.txt";

    // SMTP Configuration
            java.util.Properties props = new java.util.Properties();
            props.put("mail.smtp.auth", "true");
            props.put("mail.smtp.starttls.enable", "true");
            props.put("mail.smtp.host", "smtp.gmail.com");
            props.put("mail.smtp.port", "587");

            javax.mail.Session session = javax.mail.Session.getInstance(props,
            new javax.mail.Authenticator() {
            @Override
            protected javax.mail.PasswordAuthentication getPasswordAuthentication() {
                return new javax.mail.PasswordAuthentication(senderEmail, senderPassword);
            }
        });

    try {
        javax.mail.Message message = new javax.mail.internet.MimeMessage(session);
        message.setFrom(new javax.mail.internet.InternetAddress(senderEmail));
        message.setRecipients(javax.mail.Message.RecipientType.TO, javax.mail.internet.InternetAddress.parse(recipientEmail));
        message.setSubject("Your Bill PDF");

        // Email Body
        javax.mail.Multipart multipart = new javax.mail.internet.MimeMultipart();

        // Text part
        javax.mail.BodyPart messageBodyPart = new javax.mail.internet.MimeBodyPart();
        messageBodyPart.setText("Please find your bill attached.");
        multipart.addBodyPart(messageBodyPart);

        // Attachment part
        javax.mail.BodyPart attachmentPart = new javax.mail.internet.MimeBodyPart();
        javax.activation.DataSource source = new javax.activation.FileDataSource(filepath);
        attachmentPart.setDataHandler(new javax.activation.DataHandler(source));
        attachmentPart.setFileName(new java.io.File(filepath).getName());

        //attachmentPart.attachFile(filePath); // from your saved PDF path
        multipart.addBodyPart(attachmentPart);

        message.setContent(multipart);

        // Send the message
        javax.mail.Transport.send(message);
        javax.swing.JOptionPane.showMessageDialog(this, "Bill sent successfully to " + recipientEmail);
    } catch (HeadlessException | MessagingException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Failed to send email: " + e.getMessage());
    }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dealerbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dealerbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dealerbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dealerbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new dealerbill().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField amount;
    private javax.swing.JTextField cgstfield;
    private javax.swing.JTextField dhalltype;
    private javax.swing.JTextField grandTotalfield;
    private javax.swing.JTextField hnscode;
    private javax.swing.JTextField igstfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField ms;
    private javax.swing.JTextField partygstin;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField rate;
    private javax.swing.JTextField sgstfield;
    private javax.swing.JTextField totalfield;
    // End of variables declaration//GEN-END:variables
}
