/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbs;

/**
 *
 * @author maree
 */
import java.sql.*;
import connectionprovider.ConnectionProvider;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
public class deletelorry extends javax.swing.JFrame {

    /**
     * Creates new form deletelorry
     */
    public deletelorry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        updatename = new javax.swing.JTextField();
        industryname = new javax.swing.JTextField();
        ownername = new javax.swing.JTextField();
        drivername = new javax.swing.JTextField();
        lorrynum = new javax.swing.JTextField();
        phonenum = new javax.swing.JTextField();
        qtils = new javax.swing.JTextField();
        freights = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("DELETE LORRY DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 35, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setText("DALL INDUSTRY NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 132, 252, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("DALL INDUSTRY NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 200, 252, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setText("LORRY OWNER NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 249, 252, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setText("LORRY DRIVER NAME");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 313, 252, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setText("LORRY NUMBER");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 359, 252, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel7.setText("PHONE NUMBER");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 415, 252, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel8.setText("TOTAL QTILS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 468, 252, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel9.setText("FREIGHTS PER QTILS");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 521, 252, -1));

        updatename.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(updatename, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 129, 282, -1));

        industryname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        industryname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                industrynameActionPerformed(evt);
            }
        });
        getContentPane().add(industryname, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 197, 282, -1));

        ownername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ownername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownernameActionPerformed(evt);
            }
        });
        getContentPane().add(ownername, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 246, 282, -1));

        drivername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(drivername, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 310, 282, -1));

        lorrynum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lorrynum, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 363, 282, -1));

        phonenum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(phonenum, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 412, 282, -1));

        qtils.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        qtils.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtilsActionPerformed(evt);
            }
        });
        getContentPane().add(qtils, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 465, 282, -1));

        freights.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        freights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freightsActionPerformed(evt);
            }
        });
        getContentPane().add(freights, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 521, 282, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 129, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton2.setText("CLOSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 608, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton3.setText("RESET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 608, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 619, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\maree\\Downloads\\two-kinds-raw-beans-lentils-wooden-plate-bowls_114579-30455.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qtilsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtilsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtilsActionPerformed

    private void freightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freightsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_freightsActionPerformed

    private void industrynameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_industrynameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_industrynameActionPerformed

    private void ownernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownernameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "do you want to delete","select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            try{
                Connection con = ConnectionProvider.getConnection();
                Statement st= con.createStatement();
                st.executeUpdate("delete from lorry where dall_industry='"+updatename.getText()+"'");
                setVisible(false);
                new deletedhalsupplier().setVisible(true);
            }
            catch(SQLException e){
                
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Connection con = ConnectionProvider.getConnection();
            String query="select * from lorry where dall_industry=?";
            PreparedStatement pst =con.prepareStatement(query);
            pst.setString(1, updatename.getText());
            ResultSet rs=pst.executeQuery();
            if(rs.next())
            {
                industryname.setText(rs.getString(1));
                ownername.setText(rs.getString(2));
                drivername.setText(rs.getString(3));
                lorrynum.setText(rs.getString(4));
                phonenum.setText(rs.getString(5));
                qtils.setText(rs.getString(6));
                freights.setText(rs.getString(7));
                updatename.setEditable(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "indusrty name does not exit");
            }
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new deletelorry().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deletelorry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deletelorry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deletelorry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deletelorry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deletelorry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField drivername;
    private javax.swing.JTextField freights;
    private javax.swing.JTextField industryname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lorrynum;
    private javax.swing.JTextField ownername;
    private javax.swing.JTextField phonenum;
    private javax.swing.JTextField qtils;
    private javax.swing.JTextField updatename;
    // End of variables declaration//GEN-END:variables
}
