/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbs;
import java.sql.*;
import connectionprovider.ConnectionProvider;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
/**
 *
 * @author maree
 */
public class deletedealer extends javax.swing.JFrame {

    /**
     * Creates new form deletedealer
     */
    public deletedealer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        did = new javax.swing.JLabel();
        updateid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        companyname = new javax.swing.JTextField();
        companyaddress = new javax.swing.JTextField();
        gstinid = new javax.swing.JTextField();
        types = new javax.swing.JTextField();
        hsncode = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("DELETE DEALER DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 21, -1, -1));

        did.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        did.setText("GSTIN ID");
        getContentPane().add(did, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 154, 238, -1));

        updateid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updateid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateidActionPerformed(evt);
            }
        });
        getContentPane().add(updateid, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 151, 295, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 151, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("DEALER COMPANY NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 236, 238, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setText("DEALER ADDERSS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 301, 234, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setText("GSTIN ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 350, 234, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setText("DALL TYPES");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 399, 234, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel7.setText("HSN CODE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 455, 234, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel8.setText("DALL QUANTITY");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 501, 194, -1));

        companyname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(companyname, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 233, 292, -1));

        companyaddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(companyaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 298, 296, -1));

        gstinid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gstinid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gstinidActionPerformed(evt);
            }
        });
        getContentPane().add(gstinid, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 347, 296, -1));

        types.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(types, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 396, 296, -1));

        hsncode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(hsncode, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 452, 296, -1));

        quantity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 501, 296, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 600, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton3.setText("RESET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 600, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton4.setText("CLOSE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 600, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\maree\\Downloads\\top-view-delicious-lentils-soup-with-raw-lentils-light-background-plant-soup-color-food-seed-dish-photo.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateidActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new deletedealer().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Connection con = ConnectionProvider.getConnection();
            String query = "SELECT * FROM dealer WHERE gstin = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, updateid.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next())
            {
                companyname.setText(rs.getString(1));
                companyaddress.setText(rs.getString(2));
                gstinid.setText(rs.getString(3));
                types.setText(rs.getString(4));
                hsncode.setText(rs.getString(5));
                quantity.setText(rs.getString(6));
                updateid.setEditable(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "id does not exit");
            }
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "do you want to delete","select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            try{
                Connection con = ConnectionProvider.getConnection();
                Statement st= con.createStatement();
                st.executeUpdate("delete from dealer where gstin='"+updateid.getText()+"'");
                setVisible(false);
                new deletedealer().setVisible(true);
            }
            catch(SQLException e){
                
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void gstinidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gstinidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gstinidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deletedealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deletedealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deletedealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deletedealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new deletedealer().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField companyaddress;
    private javax.swing.JTextField companyname;
    private javax.swing.JLabel did;
    private javax.swing.JTextField gstinid;
    private javax.swing.JTextField hsncode;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField types;
    private javax.swing.JTextField updateid;
    // End of variables declaration//GEN-END:variables
}
