/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbs;

/**
 *
 * @author maree
 */
import connectionprovider.ConnectionProvider;
import javax.swing.*;
import java.sql.*;
public class dhalsupplier extends javax.swing.JFrame {

    /**
     * Creates new form dhalsupplier
     */
    public dhalsupplier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        industryname = new javax.swing.JTextField();
        industryaddress = new javax.swing.JTextField();
        uin = new javax.swing.JTextField();
        statename = new javax.swing.JTextField();
        phonenum = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        fssaiid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("DHAL SUPPLIER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setText("DALL INDUSTRY");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 118, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("ADDRESS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 167, 186, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setText("GSTIN/UIN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 216, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setText("STATE NAME");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 265, 186, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setText("CONTACT NUMBER");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 314, 186, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel7.setText("E-MAIL ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 363, 186, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel8.setText("FSSAI");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 412, 186, -1));

        industryname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        industryname.setText("ENTER DALL INDUSTRY NAME");
        industryname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                industrynameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                industrynameFocusLost(evt);
            }
        });
        industryname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                industrynameActionPerformed(evt);
            }
        });
        getContentPane().add(industryname, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 115, 283, -1));

        industryaddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        industryaddress.setText("ENTER INDUSTRY ADDRESS");
        industryaddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                industryaddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                industryaddressFocusLost(evt);
            }
        });
        getContentPane().add(industryaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 164, 283, -1));

        uin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        uin.setText("ENTER GSTIN/UIN ID");
        uin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                uinFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                uinFocusLost(evt);
            }
        });
        uin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uinActionPerformed(evt);
            }
        });
        getContentPane().add(uin, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 213, 283, -1));

        statename.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        statename.setText("ENTER STATE NAME");
        statename.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                statenameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                statenameFocusLost(evt);
            }
        });
        statename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statenameActionPerformed(evt);
            }
        });
        getContentPane().add(statename, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 262, 283, -1));

        phonenum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phonenum.setText("ENTER CONTACT NUMBER");
        phonenum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phonenumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phonenumFocusLost(evt);
            }
        });
        getContentPane().add(phonenum, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 311, 283, -1));

        mail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mail.setText("ENTER E-MAIL ID");
        mail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mailFocusLost(evt);
            }
        });
        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });
        getContentPane().add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 360, 283, -1));

        fssaiid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fssaiid.setText("ENTER FSSAI NUMBER");
        fssaiid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fssaiidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fssaiidFocusLost(evt);
            }
        });
        fssaiid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fssaiidActionPerformed(evt);
            }
        });
        getContentPane().add(fssaiid, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 409, 283, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 522, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(892, 522, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton3.setText("CLOSE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 530, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\maree\\Downloads\\wooden-bowl-spoons-raw-red-lentils-stone-background_114579-59244.jpg")); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void industrynameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_industrynameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_industrynameActionPerformed

    private void statenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statenameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_statenameActionPerformed

    private void fssaiidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fssaiidActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fssaiidActionPerformed

    private void industrynameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_industrynameFocusGained
        // TODO add your handling code here:
        if(industryname.getText().equals("ENTER DALL INDUSTRY NAME"))
        {
            industryname.setText("");
        }
        
    }//GEN-LAST:event_industrynameFocusGained

    private void industrynameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_industrynameFocusLost
        // TODO add your handling code here:
        if(industryname.getText().equals(""))
        {
            industryname.setText("ENTER DALL INDUSTRY NAME");
        }
    }//GEN-LAST:event_industrynameFocusLost

    private void industryaddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_industryaddressFocusGained
        // TODO add your handling code here:
        if(industryaddress.getText().equals("ENTER INDUSTRY ADDRESS"))
        {
            industryaddress.setText("");
        }
    }//GEN-LAST:event_industryaddressFocusGained

    private void industryaddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_industryaddressFocusLost
        // TODO add your handling code here:
        if(industryaddress.getText().equals(""))
        {
            industryaddress.setText("ENTER INDUSTRY ADDRESS");
        }
    }//GEN-LAST:event_industryaddressFocusLost

    private void uinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uinFocusGained
        // TODO add your handling code here:
        if(uin.getText().equals("ENTER GSTIN/UIN ID"))
        {
            uin.setText("");
        }
    }//GEN-LAST:event_uinFocusGained

    private void uinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uinFocusLost
        // TODO add your handling code here:
        if(uin.getText().equals(""))
        {
            uin.setText("ENTER GSTIN/UIN ID");
        }
    }//GEN-LAST:event_uinFocusLost

    private void statenameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_statenameFocusGained
        // TODO add your handling code here:
        if(statename.getText().equals("ENTER STATE NAME"))
        {
            statename.setText("");
        }
    }//GEN-LAST:event_statenameFocusGained

    private void statenameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_statenameFocusLost
        // TODO add your handling code here:
        if(statename.getText().equals(""))
        {
            statename.setText("ENTER STATE NAME");
        }
    }//GEN-LAST:event_statenameFocusLost

    private void phonenumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phonenumFocusGained
        // TODO add your handling code here:
        if(phonenum.getText().equals("ENTER CONTACT NUMBER"))
        {
            phonenum.setText("");
        }
    }//GEN-LAST:event_phonenumFocusGained

    private void phonenumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phonenumFocusLost
        // TODO add your handling code here:
        if(phonenum.getText().equals(""))
        {
            phonenum.setText("ENTER CONTACT NUMBER");
        }
    }//GEN-LAST:event_phonenumFocusLost

    private void mailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFocusGained
        // TODO add your handling code here:
        if(mail.getText().equals("ENTER E-MAIL ID"))
        {
            mail.setText("");
        }
    }//GEN-LAST:event_mailFocusGained

    private void mailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFocusLost
        // TODO add your handling code here:
        if(mail.getText().equals(""))
        {
            mail.setText("ENTER E-MAIL ID");
        }
    }//GEN-LAST:event_mailFocusLost

    private void fssaiidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fssaiidFocusGained
        // TODO add your handling code here:
        if(fssaiid.getText().equals("ENTER FSSAI NUMBER"))
        {
            fssaiid.setText("");
        }
    }//GEN-LAST:event_fssaiidFocusGained

    private void fssaiidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fssaiidFocusLost
        // TODO add your handling code here:
        if(fssaiid.getText().equals(""))
        {
            fssaiid.setText("ENTER FSSAI NUMBER");
        }
    }//GEN-LAST:event_fssaiidFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new dhalsupplier().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String dall_industry = industryname.getText();
        String address = industryaddress.getText();
        String gstin = uin.getText();
        String state = statename.getText();
        String phone_num=phonenum.getText();
        String email = mail.getText();
        String fssai = fssaiid.getText();

        
        
        
        try {
            Connection con = ConnectionProvider.getConnection();
            if (con == null) {
                JOptionPane.showMessageDialog(null, "Failed to establish a database connection.");
                 return;
            }
            String query;
            query = "INSERT INTO supplier(dall_industry,address,gstin,state,phone_num,email,fssai) VALUES (?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, dall_industry);
            pst.setString(2, address);
            pst.setString(3, gstin);
            pst.setString(4, state);
            pst.setString(5, phone_num);
            pst.setString(6, email);
            pst.setString(7, fssai);
            //pst.setString(9, quality1);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully Added");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void uinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uinActionPerformed

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dhalsupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dhalsupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dhalsupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dhalsupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new dhalsupplier().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fssaiid;
    private javax.swing.JTextField industryaddress;
    private javax.swing.JTextField industryname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField phonenum;
    private javax.swing.JTextField statename;
    private javax.swing.JTextField uin;
    // End of variables declaration//GEN-END:variables
}
