
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbs;

//import com.sun.jdi.connect.spi.Connection;
import connectionprovider.ConnectionProvider;
import javax.swing.*;
import java.sql.*;


/**
 *
 * @author maree
 */
public class newdealer extends javax.swing.JFrame {

    

    /**
     * Creates new form newdealer
     */
    public newdealer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        gstinid = new javax.swing.JTextField();
        dealercompany = new javax.swing.JTextField();
        dealeraddress = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        hsncode = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        dhallname = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("ADD NEW DEALER DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 31, -1, 40));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 795, 37, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setText("DEALER ADDRESS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 208, 224, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setText("DEALER COMPANY NAME");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 155, 273, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1273, 715, 37, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel8.setText("GSTIN ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 271, 266, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel10.setText("DALL TYPES");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 317, 273, -1));

        gstinid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gstinid.setText("ENTER GSTIN ID");
        gstinid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                gstinidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                gstinidFocusLost(evt);
            }
        });
        gstinid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gstinidActionPerformed(evt);
            }
        });
        getContentPane().add(gstinid, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 268, 384, -1));

        dealercompany.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dealercompany.setText("ENTER DEALER COMPANY NAME");
        dealercompany.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dealercompanyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dealercompanyFocusLost(evt);
            }
        });
        dealercompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dealercompanyActionPerformed(evt);
            }
        });
        getContentPane().add(dealercompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 152, 384, -1));

        dealeraddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dealeraddress.setText("ENTER DEALER ADDRESS");
        dealeraddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dealeraddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dealeraddressFocusLost(evt);
            }
        });
        getContentPane().add(dealeraddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 208, 384, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel11.setText("DHAL QUANTITY");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 418, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel13.setText("HSN CODE");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 366, 155, -1));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        quantity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        quantity.setText("ENTER  QUANTITY");
        quantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                quantityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                quantityFocusLost(evt);
            }
        });
        getContentPane().add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 418, 384, -1));

        hsncode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hsncode.setText("ENTER HSN CODE");
        hsncode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hsncodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hsncodeFocusLost(evt);
            }
        });
        hsncode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hsncodeActionPerformed(evt);
            }
        });
        getContentPane().add(hsncode, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 366, 384, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 503, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 503, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton3.setText("CLOSE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 503, -1, -1));

        dhallname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dhallname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TOOR DAL", "MASOOR DAL", "CHANA DALL", "MOONG DAL", "URAD DAL", "RAJMA", "CHAWLI", "MOTH BEANS" }));
        getContentPane().add(dhallname, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 317, 384, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\maree\\Downloads\\top-view-delicious-lentils-soup-with-raw-lentils-light-background-plant-soup-color-food-seed-dish-photo.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dealercompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dealercompanyActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dealercompanyActionPerformed

    private void gstinidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gstinidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gstinidActionPerformed

    private void hsncodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hsncodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hsncodeActionPerformed

    private void gstinidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gstinidFocusGained
        // TODO add your handling code here:
        if(gstinid.getText().equals("ENTER GSTIN ID"))
        {
            gstinid.setText("");
        }
    }//GEN-LAST:event_gstinidFocusGained

    private void gstinidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gstinidFocusLost
        // TODO add your handling code here:
        if(gstinid.getText().equals(""))
        {
            gstinid.setText("ENTER GSTIN ID");
        }
    }//GEN-LAST:event_gstinidFocusLost

    private void dealercompanyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dealercompanyFocusGained
        // TODO add your handling code here:
        if(dealercompany.getText().equals("ENTER DEALER COMPANY NAME"))
        {
            dealercompany.setText("");
        }
    }//GEN-LAST:event_dealercompanyFocusGained

    private void dealercompanyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dealercompanyFocusLost
        // TODO add your handling code here:
        if(dealercompany.getText().equals(""))
        {
            dealercompany.setText("ENTER DEALER COMPANY NAME");
        }
    }//GEN-LAST:event_dealercompanyFocusLost

    private void dealeraddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dealeraddressFocusGained
        // TODO add your handling code here:
        if(dealeraddress.getText().equals("ENTER DEALER ADDRESS"))
        {
            dealeraddress.setText("");
        }
    }//GEN-LAST:event_dealeraddressFocusGained

    private void dealeraddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dealeraddressFocusLost
        // TODO add your handling code here:
        if(dealeraddress.getText().equals(""))
        {
            dealeraddress.setText("ENTER DEALER ADDRESS");
        }
    }//GEN-LAST:event_dealeraddressFocusLost

    private void quantityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantityFocusGained
        // TODO add your handling code here:
        if(quantity.getText().equals("ENTER  QUANTITY"))
        {
            quantity.setText("");
        }
    }//GEN-LAST:event_quantityFocusGained

    private void quantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantityFocusLost
        // TODO add your handling code here:
        if(quantity.getText().equals(""))
        {
            quantity.setText("ENTER  QUANTITY");
        }
    }//GEN-LAST:event_quantityFocusLost

    private void hsncodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hsncodeFocusGained
        // TODO add your handling code here:
        if(hsncode.getText().equals("ENTER HSN CODE"))
        {
            hsncode.setText("");
        }
    }//GEN-LAST:event_hsncodeFocusGained

    private void hsncodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hsncodeFocusLost
        // TODO add your handling code here:
        if(hsncode.getText().equals(""))
        {
            hsncode.setText("ENTER HSN CODE");
        }
    }//GEN-LAST:event_hsncodeFocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new newdealer().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        // TODO add your handling code here:
        
        String company = dealercompany.getText();
        String address= dealeraddress.getText();
        String gstin = gstinid.getText();
        String dname= (String)dhallname.getSelectedItem();
        String hsn = hsncode.getText();
        String qty = quantity.getText();
        
        
        
       
        
        
        
        //if (id.isEmpty() || name.isEmpty() || phone.isEmpty() || address.isEmpty()) {
        //  JOptionPane.showMessageDialog(null, "Please fill in all fields.");
        // return;
       // }
        try {
            Connection con = ConnectionProvider.getConnection();
            if (con == null) {
                JOptionPane.showMessageDialog(null, "Failed to establish a database connection.");
                 return;
            }
            String query;
            query = "INSERT INTO dealer ( d_comapny,address,gstin,dall_types ,hsn_code,quantity ) VALUES (?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, company);
            pst.setString(2, address);
            pst.setString(3, gstin);
            pst.setString(4, dname);
            pst.setString(5, hsn);
            pst.setString(6, qty);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully Added");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newdealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newdealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newdealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newdealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new newdealer().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dealeraddress;
    private javax.swing.JTextField dealercompany;
    private javax.swing.JComboBox<String> dhallname;
    private javax.swing.JTextField gstinid;
    private javax.swing.JTextField hsncode;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField quantity;
    // End of variables declaration//GEN-END:variables
}
