/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbs;

/**
 *
 * @author maree
 */
import java.sql.*;
import connectionprovider.ConnectionProvider;
import java.awt.HeadlessException;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
public class updatedall extends javax.swing.JFrame {

    /**
     * Creates new form updatedall
     */
    public updatedall() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        industryname = new javax.swing.JTextField();
        dallname = new javax.swing.JTextField();
        hsncode = new javax.swing.JTextField();
        bagnum = new javax.swing.JTextField();
        packnum = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        rate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        updatename = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("UPDATE DALL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setText("DALL INDUSTRY NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, 250, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("DALL NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 250, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setText("HSN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, 250, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setText("BAGS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, 250, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setText("PACKING");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 410, 250, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel7.setText("QUANTITY");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 250, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel8.setText("RATE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 510, 250, -1));

        industryname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        industryname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                industrynameActionPerformed(evt);
            }
        });
        getContentPane().add(industryname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 170, 341, -1));

        dallname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dallname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dallnameActionPerformed(evt);
            }
        });
        getContentPane().add(dallname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 230, 341, -1));

        hsncode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hsncode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hsncodeActionPerformed(evt);
            }
        });
        getContentPane().add(hsncode, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 290, 341, -1));

        bagnum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(bagnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 350, 341, -1));

        packnum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(packnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 410, 341, -1));

        quantity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 460, 341, -1));

        rate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 510, 341, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel9.setText("DALL INDUSTRY NAME");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, 250, -1));

        updatename.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updatename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatenameActionPerformed(evt);
            }
        });
        getContentPane().add(updatename, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 100, 341, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 100, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 640, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton3.setText("RESET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 640, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton4.setText("CLOSE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 640, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\maree\\Downloads\\wooden-bowl-spoons-raw-red-lentils-stone-background_114579-59244.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 930));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void industrynameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_industrynameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_industrynameActionPerformed

    private void dallnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dallnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dallnameActionPerformed

    private void hsncodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hsncodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hsncodeActionPerformed

    private void updatenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatenameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String name;
        name = updatename.getText();
        String dall_industry = industryname.getText();
        String d_name= dallname.getText();
        BigInteger hsn = new BigInteger(hsncode.getText());
        int bag = Integer.parseInt(bagnum.getText());
        int pack = Integer.parseInt(packnum.getText());
        BigDecimal qty = new BigDecimal(quantity.getText().trim());
        BigDecimal ratevalue = new BigDecimal(rate.getText());
        BigDecimal total_amount = ratevalue.multiply(qty);
        try
        {
            Connection con = ConnectionProvider.getConnection();
            Statement st= con.createStatement();
            st.executeUpdate("update dall_supplier set dall_industry='" + dall_industry + "',"
            + "dall_name='" + d_name + "',"
            + "hsn='" + hsn + "',"
            + "bags='" + bag + "',"
            + "packing='" + pack + "',"
            + "quantity='" + qty + "',"
            + "rate='" + ratevalue + "' ,"
            + "amount='" + total_amount + "' "
            + "where dall_industry='" + name + "'");

            JOptionPane.showMessageDialog(null,"sucessfully updated");
            setVisible(false);
            new updatedealer().setVisible(true);
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new updatedall().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
        
        Connection con = ConnectionProvider.getConnection();
        String query="select * from dall_supplier where  dall_industry =?";
        PreparedStatement pst =con.prepareStatement(query);
        pst.setString(1, updatename.getText());
        ResultSet rs=pst.executeQuery();

        if (rs.next()) {
            industryname.setText(rs.getString(1));
            dallname.setText(rs.getString(2));
            hsncode.setText(rs.getString(3));
            bagnum.setText(rs.getString(4));
            packnum.setText(rs.getString(5));
            quantity.setText(rs.getString(6));
            rate.setText(rs.getString(7));
            updatename.setEditable(false);
        }
            
        }
        catch(HeadlessException e)
        {
            
        } catch (SQLException ex) {
            Logger.getLogger(updatedealer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatedall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatedall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatedall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatedall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatedall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bagnum;
    private javax.swing.JTextField dallname;
    private javax.swing.JTextField hsncode;
    private javax.swing.JTextField industryname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField packnum;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField rate;
    private javax.swing.JTextField updatename;
    // End of variables declaration//GEN-END:variables
}
