/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbs;

import java.sql.*;
import connectionprovider.ConnectionProvider;
import java.awt.HeadlessException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author maree
 */
public class updatesupplier extends javax.swing.JFrame {

    /**
     * Creates new form updatesupplier
     */
    public updatesupplier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        industryname = new javax.swing.JTextField();
        industryaddress = new javax.swing.JTextField();
        gstinid = new javax.swing.JTextField();
        statename = new javax.swing.JTextField();
        phonenum = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        fssaiid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        uinid = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("UPDATE SUPPLIER DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(817, 23, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 222, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("ADDRESS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 216, 222, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setText("GSTIN/UIN ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 265, 222, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setText("STATE NAME");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 317, 222, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setText("CONTACT NUMBER");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 364, 222, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel7.setText("E-MAIL ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 413, 222, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel8.setText("FSSAI");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 462, 222, -1));

        industryname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        industryname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                industrynameActionPerformed(evt);
            }
        });
        getContentPane().add(industryname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 159, 236, -1));

        industryaddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        industryaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                industryaddressActionPerformed(evt);
            }
        });
        getContentPane().add(industryaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 211, 236, -1));

        gstinid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gstinid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gstinidActionPerformed(evt);
            }
        });
        getContentPane().add(gstinid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 260, 236, -1));

        statename.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(statename, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 312, 236, -1));

        phonenum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phonenum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenumActionPerformed(evt);
            }
        });
        getContentPane().add(phonenum, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 361, 236, -1));

        mail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 410, 236, -1));

        fssaiid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(fssaiid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 459, 236, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 538, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 538, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton3.setText("CLOSE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1343, 538, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel9.setText("GSTIN/UIN ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 122, 222, -1));

        uinid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(uinid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 119, 231, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton4.setText("SEARCH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1343, 119, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel10.setText("DALL INDUSTRY");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 158, 222, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\maree\\Downloads\\wooden-bowl-spoons-raw-red-lentils-stone-background_114579-59244.jpg")); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void industrynameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_industrynameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_industrynameActionPerformed

    private void industryaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_industryaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_industryaddressActionPerformed

    private void gstinidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gstinidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gstinidActionPerformed

    private void phonenumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenumActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new updatesupplier().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id;
        id = uinid.getText();
        String dall_industry = industryname.getText();
        String address= industryaddress.getText();
        String gstin = gstinid.getText();
        String state = statename.getText();
        String phone_num=phonenum.getText();
        String email = mail.getText();
        String fssai = fssaiid.getText();
        try
        {
            Connection con = ConnectionProvider.getConnection();
            Statement st= con.createStatement();
            st.executeUpdate("update supplier set dall_industry='" + dall_industry + "',"
            + "address='" + address + "',"
            + "gstin='" + gstin + "',"
            + "state='" + state + "',"
            + "phone_num='" + phone_num + "',"
            + "email='" + email + "',"
            + "fssai='" + fssai + "' "
            + "where gstin='" + id + "'");

            JOptionPane.showMessageDialog(null,"sucessfully updated");
            setVisible(false);
            new updatedealer().setVisible(true);
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:try{
        try {
        
        Connection con = ConnectionProvider.getConnection();
        String query="select * from supplier where gstin=?";
        PreparedStatement pst =con.prepareStatement(query);
        pst.setString(1, uinid.getText());
        ResultSet rs=pst.executeQuery();

        if (rs.next()) {
            industryname.setText(rs.getString(1));
            industryaddress.setText(rs.getString(2));
            gstinid.setText(rs.getString(3));
            statename.setText(rs.getString(4));
            phonenum.setText(rs.getString(5));
            mail.setText(rs.getString(6));
            fssaiid.setText(rs.getString(7));
            uinid.setEditable(false);
        }
            
        }
        catch(HeadlessException e)
        {
            
        } catch (SQLException ex) {
            Logger.getLogger(updatedealer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatesupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatesupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatesupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatesupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new updatesupplier().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fssaiid;
    private javax.swing.JTextField gstinid;
    private javax.swing.JTextField industryaddress;
    private javax.swing.JTextField industryname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField phonenum;
    private javax.swing.JTextField statename;
    private javax.swing.JTextField uinid;
    // End of variables declaration//GEN-END:variables
}
